services:
  # 1. The Python Face Recognition API
  - type: web
    name: smart-attend-python-api
    env: python
    rootDir: python-api
    buildCommand: pip install -r requirements.txt gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  # 2. The Node.js Backend Server
  - type: web
    name: smart-attend-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PYTHON_API_URL
        fromService:
          type: web
          name: smart-attend-python-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false # You will paste your MongoDB link here in the Render Dashboard

  # 3. The React Frontend
  - type: web
    name: smart-attend-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: smart-attend-backend
          envVarKey: RENDER_EXTERNAL_URL
